#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HalloweenSoundGenerator.Resource", IsApplication=true)]

namespace HalloweenSoundGenerator
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int HalloweenButton = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int HalloweenButtonPressed = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int pumpkin = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int effect_now = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int imageView1 = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int start_stop = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int creepy_whispers_2 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int creepy_whispers_2_1 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int demonic_woman_scream = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int evil_laugh = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int evil_witch_cackle = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int Female_Scream_Horror138499973 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int ghost_voice_i_see_you = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int ghost_voice_why_cant_you_see_me = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int halloween_001_wav_120b = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int oh_god_wah = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int Scary1449371204 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int zombie = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int zombie_brains = 2131034124;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
